### ISSUE TITLE
Provide ability to setup a new repository

### ISSUE THREAD

**Issue by Totktonada** [tarantool/rws#16]
Creation of a repository for a new tarantool release series assumes that we should copy all modules, connectors and so on into the new repository. It would be nice to automate this action.

Since the RWS service should be general enough (at least in a future), I propose to implement this functionality in some general way to allow another repository creation flow for non-tarantool repositories.

**Comment by Totktonada** [comment]
Alternative: implement ability to expose a set of different directories as a single repository.

This way we'll push tarantool packages to a specific directory (splitted by a release series) and push a module to a common directory (which is part of all per-series repositories).

**Comment by LeonidVas** [comment]
OMG! It might be better to have separate repositories for modules and hide the connection of all necessary repositories by installing the appropriate .deb package (which will connect all the necessary repositories).

**Comment by Totktonada** [comment]
Maybe. However, when we discussing it with @igormunkin, there was a point that a user should not bother about all our internal problems and just enable one repository.

There is a task about package that will install repositories: https://github.com/tarantool/tarantool/issues/5259

`installer.sh` already setup the separate `modules` repository (however there is no decision, whether we should expand this approach to all modules and tools, because of the point above).

**Comment by Totktonada** [comment]
Raw idea: remember packages uploaded to all tarantool series and copy them when bootstrapping a new tarantool series.

**Comment by Totktonada** [comment]
There is a related discussion about the separate modules repository: https://github.com/tarantool/doc/issues/2230.

**Comment by rosik** [comment]
If you ask my opinion, I support extending and developing a separate `modules` repo. And rename it however you want, if necessary.

**Comment by Totktonada** [comment]
My main point: let's do it consistently. If we move everything aside tarantool to another repository (that will not be splitted by tarantool version), let's do it for all modules, connectors and other components.

**Comment by Totktonada** [comment]
Summary:

1. We have `1.10`, `{2.1..2.8}` repositories, where modules are shipped. We'll continue ship them here (including new module versions).
2. We have the new `modules` repository. All modules will go here as well.
3. We'll NOT ship modules to the new series-2 repositories.

As result when we'll setup a repository for a new release series, we can start from the empty repository. Nothing more to track here.

----

I would also note that after #48 we'll have a convenient URL to push a module to all appropriate repositories.
