### ISSUE TITLE
new release policy: support the new repository layout

### ISSUE THREAD

**Issue by Totktonada** [tarantool/rws#24]
The main discussion about the new release policy is [here](https://github.com/tarantool/tarantool/discussions/6182).

See https://github.com/tarantool/tarantool/issues/6185.

**Comment by LeonidVas** [comment]
Note: before starting to implement the feature, it is needed to add a comment of what changes are planned (what we have now and what we want to have at the end of the task).

**Comment by LeonidVas** [comment]
AFAIU we must to do the following:
- remove "live" from "repo_kind"
- add "pre-release" to "repo_kind"
- add "series-2" to "tarantool_series"
