### ISSUE TITLE
Create a tool for backup repositories

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/rws#8]
There are no backups of the repositories and I think this is dangerous. I propose to create a script for this purpose and put it to `tools` directory.

**Comment by avtikhon** [comment]
Right, it is extremely needed, due to any tiny error may cause complete repository destruction. There are a few ways to resolve the issue. Ideally S3 should not be used as standalone place for repository storage it should be used as part of [CDN](https://habr.com/ru/company/webzilla/blog/236511/#:~:text=CDN%20%E2%80%94%20%D1%81%D0%BE%D0%BA%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BE%D1%82%20content%20delivery,%D0%B5%D1%81%D1%82%D1%8C%20%E2%80%9C%D1%81%D0%B5%D1%82%D1%8C%20%D0%B4%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B8%20%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D1%82%D0%B0%E2%80%9D.) to store the packages - in this scheme it would be backed up automatically. Anyway we use S3 as the only storage place for packages and it should be controlled by any tool which can check the changes either blind backup bucket complete.

**Comment by LeonidVas** [comment]
https://blog.programster.org/backing-up-s3-bucket-with-duplicity
This tool is used for backups and uploads it to S3, but it might be useful too:
https://pypi.org/project/duplicity-backup-s3/

**Comment by LeonidVas** [comment]
> Right, it is extremely needed, due to any tiny error may cause complete repository destruction. There are a few ways to resolve the issue. Ideally S3 should not be used as standalone place for repository storage it should be used as part of [CDN](https://habr.com/ru/company/webzilla/blog/236511/#:~:text=CDN%20%E2%80%94%20%D1%81%D0%BE%D0%BA%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BE%D1%82%20content%20delivery,%D0%B5%D1%81%D1%82%D1%8C%20%E2%80%9C%D1%81%D0%B5%D1%82%D1%8C%20%D0%B4%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B8%20%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D1%82%D0%B0%E2%80%9D.) to store the packages - in this scheme it would be backed up automatically. Anyway we use S3 as the only storage place for packages and it should be controlled by any tool which can check the changes either/with full bucket backup by scheduler.

When you talked about the "check" tool, did you mean a tool that will compare meta information to actual uploaded packages, or something else?

**Comment by LeonidVas** [comment]
While working on the task, I looked at two popular backup tools "duplicity" and "restic". After a few tests, I preferred the second one because it is multithreaded (but in our case it doesn't make a lot of profit because the bottleneck is getting the list of files from S3 over s3fs, maybe I'll come up with in the future, but now I don't know, how to optimize it) and it also has a good [deduplication](https://restic.readthedocs.io/en/v0.3.3/Design/#backups-and-deduplication), which is cool in our case when we upload the same module packages to multiple repositories.

**Comment by LeonidVas** [comment]
Backup of the "release" suite
```
┌─[leonid@vasya-hp]─[~/work/mail/tasks/S3]
└──╼ ~/work/mail/rws/tools/rws_backup.sh backup                                     
created restic repository 89a2f03333 at /home/leonid/work/mail/tasks/S3/s3_restic_backup_release

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
repository 89a2f033 opened successfully, password is correct
created new cache in /home/leonid/.cache/restic
no parent snapshot found, will read all files

Files:       16354 new,     0 changed,     0 unmodified
Dirs:         3191 new,     0 changed,     0 unmodified
Added to the repo: 12.175 GiB

processed 16354 files, 16.251 GiB in 1:39:57
snapshot a33c35c6 saved

```

**Comment by avtikhon** [comment]
> > Right, it is extremely needed, due to any tiny error may cause complete repository destruction. There are a few ways to resolve the issue. Ideally S3 should not be used as standalone place for repository storage it should be used as part of [CDN](https://habr.com/ru/company/webzilla/blog/236511/#:~:text=CDN%20%E2%80%94%20%D1%81%D0%BE%D0%BA%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BE%D1%82%20content%20delivery,%D0%B5%D1%81%D1%82%D1%8C%20%E2%80%9C%D1%81%D0%B5%D1%82%D1%8C%20%D0%B4%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B8%20%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D1%82%D0%B0%E2%80%9D.) to store the packages - in this scheme it would be backed up automatically. Anyway we use S3 as the only storage place for packages and it should be controlled by any tool which can check the changes either/with full bucket backup by scheduler.
> 
> When you talked about the "check" tool, did you mean a tool that will compare meta information to actual uploaded packages, or something else?

RIght, meta information is the list of all already uploaded packages and its better to upload new packages exactly only that are needed, but not update all the meta information on the current list of packages.
