### ISSUE TITLE
Create AlmaLinux 8/9 repositories for modules

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/rws#96]
According to my information, AlmaLinux is popular inside VK. For example, we were asked to create packages for AlmaLinux 9, see:
https://jira.vk.team/browse/TNT-1117

But there is no such repository here:

https://rws.tarantool.org/release/modules

We probably need to create it.

**Comment by ylobankov** [comment]
Actually, there is no need to create such repos. We already made RWS [support](https://github.com/tarantool/rws/commit/cfbb045fd0bccbbfe79695c871d544a7024e5d76) these distros. The repositories will be created automatically when the corresponding package will be pushed.
